%script to extract analyzed data from ws6*.MAT files and generate plots


%% Load Data
pn_ws6='Results2/MAT'; %path to MAT files generated by plot_ws6
xlsfile='Results2/ptvpiv_20121006.xlsx';
sheet1='1006_ws6Analysis';
sheet2='ADV';
s=loadxls_struct(xlsfile,sheet1); %load input from xls as struct
adv=loadxls_struct(xlsfile,sheet2); %load input from xls as struct
in=logical([s.flag1,s.flag2,s.flag3,s.flag4]); %only requested and valid cases
I=find(all(in,2)); %gives indices to requested cases
clear a
for k=1:length(I);
    K=I(k); %index into struct: s
    matfile=fullfile(pn_ws6,strrep(s.file_ptv{K},'ptv_','ws6_'));
    a(k)=load(matfile);
end

%Time Data
%Construct PICS time from filename
fn={a.filename}'; %store the filenames in a cell array
dstr=regexp(fn,'\d*','match','once'); %extract all numeric content from cell array
mtime=datenum(dstr,'yyyymmddHHMMSS'); %convert string to serial time with yyyymmddHHMMSS format
%datestr(mtime) %checks the conversion
%Construct ADV time from time string
adv.mtime=datenum(adv.time);

%% Plot Data
figure(5);
picsfield='ws50m';
plot(mtime,[a.(picsfield)],'bo',adv.mtime,adv.ws_adv,'rx',...
    'LineWidth',2)
datetick('x')
set(gca,'YLim',[0,1])
ylabel('\itW_s\rm  [mm\cdots^{ -1}]')
xlabel('time')
legend({['pics-',picsfield],'adv'},'Interpreter','none')
